### ISSUE TITLE
Should we ignore branch deletions unconditionally?

### ISSUE THREAD

**Issue by dabrahams** [ryppl/Boost2Git#15]
See the commit message on a203c9af2a.  I'm not 100% certain, but I think perhaps that logic applies equally well to _any_ branch (not just master).  What do you think?

**Comment by dabrahams** [comment]
I think the diagnosis of #6 indicates that we shouldn't.  Please consider this question, though, for the other cases.

**Comment by purpleKarrot** [comment]
svn2git creates backups when branches are deleted. The reason is that when the another branch is created with the same name those two branches should not be connected.

What might be better: when a branch is deleted, flag it as deleted but do not actually delete it. When branch is recreated (ie. when changes are made to a branch flagged deleted), create a backup and delete it.

**Comment by dabrahams** [comment]
I'm satisfied that what we're doing right now is adequate.

**Comment by purpleKarrot** [comment]
OK, so I will just silence the warnings.
